### ISSUE TITLE
SH20T: Error 400 at connection

### ISSUE THREAD

**Issue by e-tplus** [NickStallman/home-assistant-repo#27]
Hello, I cannot connect to the Winet-S2 of my SH20T. Log:

`2024-10-18 10:30:32 warn: Reconnecting to Winet 
2024-10-18 10:31:04 error: Websocket error: Unexpected server response: 400 {
  stack: 'Error: Unexpected server response: 400\n' +
    '    at ClientRequest.<anonymous> (/usr/src/app/node_modules/ws/lib/websocket.js:912:7)\n' +
    '    at ClientRequest.emit (node:events:519:28)\n' +
    '    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)\n' +
    '    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\n' +
    '    at TLSSocket.socketOnData (node:_http_client:540:22)\n' +
    '    at TLSSocket.emit (node:events:519:28)\n' +
    '    at addChunk (node:internal/streams/readable:559:12)\n' +
    '    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n' +
    '    at Readable.push (node:internal/streams/readable:390:5)\n' +
    '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)',
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [
    Error: Unexpected server response: 400
        at ClientRequest.<anonymous> (/usr/src/app/node_modules/ws/lib/websocket.js:912:7)
        at ClientRequest.emit (node:events:519:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
        at TLSSocket.socketOnData (node:_http_client:540:22)
        at TLSSocket.emit (node:events:519:28)
        at addChunk (node:internal/streams/readable:559:12)
        at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
        at Readable.push (node:internal/streams/readable:390:5)
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)
  ]`

Credentials should be correct.

**Comment by e-tplus** [comment]
Solved. SSL must not be activated.
